[build]
  command = "npm run build && npm run scully"
  functions = "./functions"
  publish = "dist/TIPI-KNAPA/static"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
